# Site settings
title:Plumbing Near You
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rudyy620.github.io/Plumbing-Near-You/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
